### ISSUE TITLE
希望支持autolayout 修复iPad上的问题

### ISSUE THREAD

**Issue by jiazufei** [12207480/TYSlidePageScrollView#1]
在iPad上横竖屏视图变化会有问题，请修复
初始化的时候，使用Masonry适配屏幕，就无法显示了

TYSlidePageScrollView *slidePageScrollView = [[TYSlidePageScrollView alloc]initWithFrame:CGRectZero];
    slidePageScrollView.pageTabBarIsStopOnTop = _pageTabBarIsStopOnTop;
    slidePageScrollView.dataSource = self;
    [self.view addSubview:slidePageScrollView];
    _slidePageScrollView = slidePageScrollView;
    
    [slidePageScrollView makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.view.top);
        make.left.equalTo(self.view.left);
        make.bottom.equalTo(self.view.bottom);
        make.right.equalTo(self.view.right);
    }];

**Comment by 12207480** [comment]
会的

**Comment by 12207480** [comment]
已经更新 支持
