### ISSUE TITLE
self.viewControllers中使用包含UICollectionView的控制器发生错误

### ISSUE THREAD

**Issue by JimWithJiang** [12207480/TYSlidePageScrollView#2]
您好，我想在self.viewControllers中使用包含UICollectionView的控制器，下面2种办法分别会显示错误：希望您能帮忙解决下，谢谢了。具体如下：直接添加一个UICollectionViewController会在- (UIScrollView *)slidePageScrollView:(TYSlidePageScrollView *)slidePageScrollView pageVerticalScrollViewForIndex:(NSInteger)index中返回nil,或者使用包含UICollectionView的UIViewController会报 [__NSArrayM insertObject:atIndex:]: object cannot be nil，在- (void)updatePageViews中pageVerScrollView为空。

**Comment by 12207480** [comment]
// the viewController need conform to **UIViewControllerDisplayViewDelegate**
@property (nonatomic, strong) NSArray   *viewControllers;

**Comment by JymnChen** [comment]
有 UICollectionView 对应的 Demo 吗？
