### ISSUE TITLE
容器里的控制器无法导航push到另一个，这是怎么回事啊？？

### ISSUE THREAD

**Issue by CODE4APPLE** [12207480/TYSlidePageScrollView#4]

**Comment by CODE4APPLE** [comment]
我发现这里竟然没有将childVC add 上去。😓
if (![self.viewControllers containsObject:viewController]) {
        // don't forget set frame and addChildViewController
        
        [self addChildViewController:viewController];
        [viewController willMoveToParentViewController:self];
        viewController.view.frame = self.view.frame;
        [viewController didMoveToParentViewController:self];
    }

**Comment by 12207480** [comment]
哪里？

**Comment by CODE4APPLE** [comment]
//TYSlidePageScrollViewDataSource的数据源协议方法里

**Comment by 12207480** [comment]
谢谢 找到了

**Comment by 12207480** [comment]
写错了 应该是childViewControllers

**Comment by CODE4APPLE** [comment]
恩恩。大神后面可以将控制器懒加载完善一下吗？

**Comment by 12207480** [comment]
我这个用懒加载 比较复杂 还没有思路
