### ISSUE TITLE
HeaderView 出现这种问题是什么 

### ISSUE THREAD

**Issue by Eliothu** [12207480/TYSlidePageScrollView#5]
![Uploading testGifaaaa.gif…]()
如图所示 2个问题 1是headerview 滑动问题  在你的Demo上该就没问题  我的没加MJ   
2是 tableview上面的莫名的一段宽度  切换其他的又好了

**Comment by Eliothu** [comment]
![Uploading 屏幕快照 2015-10-22 上午9.50.37.png…]()

**Comment by 12207480** [comment]
图片看不到

**Comment by Eliothu** [comment]
我再试试  你有其他的联系方式么  git上传 好卡

**Comment by 12207480** [comment]
qq 122074809

**Comment by 12207480** [comment]
HeaderView 在plain下有问题
