### ISSUE TITLE
collectionView

### ISSUE THREAD

**Issue by T1200** [12207480/TYSlidePageScrollView#9]
collection貌似加载不上去啊，我查看了scrollerview的创建，按理说，上面可以加载任何的视图控制器，只要在当前滑动的页面，将试图控制器的scrollerView属性传出来就可以，但是我尝试了，总是崩溃
[LD个人中心界面.zip](https://github.com/12207480/TYSlidePageScrollView/files/80973/LD.zip)

**Comment by T1200** [comment]
希望得到解决

**Comment by itdongbaojun** [comment]
我想知道关于UICollectionView的问题是怎么解决的？我也遇到了同样的问题。

**Comment by itdongbaojun** [comment]
@T1200 你的问题是怎么解决的呢？我也遇到了同样的问题，完全理解不了是为什么，只要按照协议挺能相应的UIScrollView子类就行了，为什么不可以呢。

**Comment by 12207480** [comment]
我晚上看看
